name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::jupyterlab=3.0.12
  - conda-forge::mlflow=2.6.0 #2.1.1
  - conda-forge::numpy=1.24.1
  - conda-forge::cookiecutter=2.5.0 #1.7.2
  - conda-forge::hydra-core=1.3.2 #1.0.6
  - conda-forge::matplotlib=3.6.2
  - conda-forge::pandas=1.2.3
  - conda-forge::git=2.30.2
  - conda-forge::pip=23.3.1 #20.3.3
  - pip:
      - wandb==0.16.2 #0.13.9